config/routes.rb
Rails.application.routes.draw do
  root 'coins#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    resources :coins
    resources :prices
  end



  resources :coins do

    resources :comments
  end

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :picture, presence: true
  has_many :comments
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :title, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5  }
  belongs_to :coin
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :coins, dependent: :destroy
  has_many :comments, dependent: :destroy

  def admin?
    role == "admin"
  end

  mount_uploader :avatar, AvatarUploader
end

app/controllers/api/coins_controller.rb
class Api::CoinsController < ApiController
  def index
    render json: Coin.all
  end

  def show
    render json: { coin: Coin.find(params[:id])}
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me, :avatar, :avatar_cache) }
   devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :password, :password_confirmation, :current_password, :avatar, :avatar_cache, :remove_avatar) }
 end
end

app/controllers/coins_controller.rb
require 'cryptocompare'
require 'json'
class CoinsController < ApplicationController

  before_action :authorize_user, except: [:index, :show]

  def index
  end

  def show
    @coin = Coin.find(params[:id])

    

    @coin_price = Cryptocompare::Price.find(@coin.name, 'USD')
    @coin_hist = Cryptocompare::HistoDay.find(@coin.name, 'USD')
    @coin_price_key = @coin_price.keys[0]
    @coin_price_value = @coin_price.values[0]["USD"]
    # @coin_deposit_date =
    # @historical_price = Cryptocompare::PriceHistorical.find(@coin.name, 'USD', {'ts' => 1452680400})
    # @historical_price_key = @historical_price.keys[0]
    # @historical_price_value = @historical_price.values[0]["USD"]
    #

    @comments = Comment.where(coin_id: @coin.id)
      @comment_rating = 0
      @comments.map { |comment|
        @comment_rating += comment.rating
      }
      @comment_rating = @comment_rating/@comments.length rescue 0


  end

  def new
    @user = current_user
    @coin = Coin.new
  end

  def create
    @coin = Coin.new(coin_params)
    @coin.user = current_user

    if @coin.save
      redirect_to coin_path(@coin.id)
      flash[:notice] = 'Coin added successfully'
    else
      flash[:error] = @coin.errors.full_messages.join(", ")
      render :new
    end

  end

  def edit
    @coin = Coin.find(params[:id])
  end

  def update
    @coin = Coin.find(params[:id])

    if @coin.update(coin_params)
      redirect_to coin_path(@coin)
    else
      render :edit
    end
  end

  def destroy
    @coin = Coin.find(params[:id])
    @coin.destroy
    redirect_to root_path
  end

  protected

  def coin_params
    params.require(:coin).permit(:name, :picture, :description)
  end


  def user_params
    params.require(:user).permit(:email, :encrypted_password)
  end

  def authorize_user
    if !user_signed_in?
      raise ActionController::RoutingError.new("Not Found")
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authorize_user, except: [:index, :show]

  def new
    @coin = Coin.find(params[:coin_id])
    @comment = Comment.new
  end

  def create
    @coin = Coin.find(params[:coin_id])
    @increase = true

    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id

    @comment.coin = @coin
    @coin_price = Cryptocompare::Price.find(@coin.name, 'USD')
    @coin_price_value = @coin_price.values[0]["USD"]

    #date translation to unix
    @unix_parse = Date.parse(@comment.date)
    @coin_deposit_date = @unix_parse.to_time.to_i

    @initial_coin_deposit = @comment.initial_coin_deposit
    @historical_price = Cryptocompare::PriceHistorical.find(@coin.name, 'USD', {'ts' => @coin_deposit_date})
      # if Cryptocompare::PriceHistorical.find(@coin.name, 'USD', {'ts' => @coin_deposit_date}) == nil
      #   flash[:error] = @comment.errors.full_messages.join(", ")
      # else
      #   @historical_price = Cryptocompare::PriceHistorical.find(@coin.name, 'USD', {'ts' => @coin_deposit_date})
      # end

    if !@historical_price.nil?
      @initial_investment_value = (@historical_price[@coin.name]["USD"] * @initial_coin_deposit)
      @current_investment_value = (@coin_price_value * @initial_coin_deposit)

      if @initial_investment_value < @current_investment_value
        @increase_css_class = 'increase'
        @comment.value = (((@current_investment_value - @initial_investment_value) / @initial_investment_value) * 100).round
      else
        @increase_css_class = 'decrease'
        @comment.value = -1 * (((@initial_investment_value - @current_investment_value) / @initial_investment_value) * 100).round
      end
    else
      render status: :not_found
    end

    # @comment.value = ((@coin_price_value * @comment.initial_coin_deposit) - (@historical_price[@coin.name]["USD"] * @comment.initial_coin_deposit))


    if @comment.save
      redirect_to coin_path(@coin.id)
      flash[:notice] = "Comment added successfully"
    else

      @comments = @coin.comments

      flash[:error] = @comment.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @coin = Coin.find(params[:coin_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @coin = Coin.find(params[:coin_id])

    if @comment.update(comment_params)
      redirect_to coin_path(@coin)
    else
      render :edit
    end
  end

  def destroy
    @coin = Coin.find(params[:coin_id])
    #@comments = Comment.where(coin_id: @coin.id)
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to coin_path(params[:coin_id])
  end

  def show
    @comment = Comment.find(params[:id])
    #shit i added
    #
    # @unix_parse = Date.parse(@comment.date)
    # @coin_deposit_date = @unix_parse.to_time.to_i
    # @initial_coin_deposit = comment.initial_coin_deposit
    #
    # @historical_price = Cryptocompare::PriceHistorical.find(@coin.name, 'USD', {'ts' => @coin_deposit_date})
    #
    # @comment.value = @coin_price_value - (@historical_price * @initial_coin_deposit)
    #
    # @historical_price_key = @historical_price.keys[0]
    # @historical_price_value = @historical_price.values[0]["USD"]

  end

  private

  def comment_params
    params.require(:comment).permit(:title, :rating, :price, :user_id, :coin_id, :body, :value, :date, :initial_coin_deposit)
  end

  def coin_params
    params.require(:coins).permit(:id)
  end

  def authorize_user
    if !user_signed_in?
      raise ActionController::RoutingError.new("Not Found")
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_user

  def index
    @users = User.all
  end

  def show
   @user = current_user
   @User.find(params[:id])
  end

  def update
    @user = current_user
    @user.update(user_params)
    @user.save
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def authorize_user
    if !user_signed_in? || !current_user.admin?
      raise ActionController::RoutingError.new("Not Found")
    end
  end

  def user_params
    params.require(:user).permit(:email, :avatar)
  end

end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/coins/edit.html.erb
<h1>Edit <%= @coin.name %></h1>
<%= form_for(@coin) do |f| %>
<div class="field">
  <%= f.label :name %>
  <%= f.text_area :name %>
</div>

<div class="field">
  <%= f.label :picture %>
  <%= f.text_area :picture %>
</div>

<div class="field">
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>

<div class="actions">
  <%= f.submit "Add Coin" %>
</div>
<% end %>

app/views/coins/index.html.erb
<div id="app">
</div>

app/views/coins/new.html.erb
<h1>Submit Coin</h1>

<%= form_for(@coin) do |f| %>
<div class="field">
  <%= f.label :name %>
  <%= f.text_area :name %>
</div>

<div class="field">
  <%= f.label :picture %>
  <%= f.text_area :picture %>
</div>

<div class="field">
  <%= f.label :description %>
  <%= f.text_area :description %>
</div>

<div class="actions">
  <%= f.submit "Add Coin" %>
</div>
<% end %>

app/views/coins/show.html.erb
<div>
  <%= link_to "Back", coins_path, class: 'button'  %>
</div>

<div class="row">
  <div id=class="text-center padder tile">
    <h1 id="title"> <%= @coin.name %> </h1>
    <h2> <script type="text/javascript">
            baseUrl = "https://widgets.cryptocompare.com/";
            var scripts = document.getElementsByTagName("script");
            var embedder = scripts[ scripts.length - 1 ];
            (function (){
            var appName = encodeURIComponent(window.location.hostname);
            if(appName==""){appName="local";}
            var s = document.createElement("script");
            s.type = "text/javascript";
            s.async = true;
            var theUrl = baseUrl+'serve/v1/coin/chart?fsym=<%=@coin.name%>&tsym=USD';
            s.src = theUrl + ( theUrl.indexOf("?") >= 0 ? "&" : "?") + "app=" + appName;
            embedder.parentNode.appendChild(s);
            })();
          </script>
     </h2>

  </div>
</div>

<% #PICTURE %>
<div class="row">
  <div class="text-center padder cointile">
    <img class="coinimg" src=<%= @coin.picture %> alt=<%= @coin.name %>>
    <p> <%= @coin.description %></p>
    <div> Average Stability Score:</div>
    <% for i in 1..@comment_rating %>
      <span><i class="fab fa-bitcoin"></i></span>
    <% end %>



    <div>Current price of <%= @coin_price_key %> in USD $<%= @coin_price_value %> </div>


    <% if current_user != nil %>
      <% if current_user.admin? %>
        <%= link_to "Delete Coin", coin_path(@coin.id), class: 'button', method: :delete, data: {confirm: 'Are your sure?'} %>
        <%= link_to "Edit Coin", edit_coin_path(@coin.id), class: 'button' %>
      <% end %>
    <% end %>

  </div>
</div>




<!-- <div class="row">
  <div class="text-center tile padder ">



  </div>
</div> -->

<div class="row">
  <div class="text-center tile padder">
    <h2> Comments for <%= @coin.name %> </h2>
    <% if user_signed_in? %>
      <%= link_to "Add Comment", new_coin_comment_path(@coin), class: 'button' %>
    <% end %>
  </div>
</div>



    <ul>
      <% @comments.each do |comment| %>
        <div class="row">
          <div class="text-center commenttile padder">
          <div class="commenttitle"><h3> <%= comment.title  %> </h3>
            <p class="floatright"> <%= comment.body %> </p>

          </div>

          <div class="commentinfo">
            <p> Stability Rating:
            <% for i in 1..comment.rating %>
              <span><i class="fab fa-bitcoin"></i></span>
            <% end %> </p>

            <p> Initial investment date <%= comment.date %> </p>

            <p> Amount of Coins Invested: <%= comment.initial_coin_deposit %></p>

            <% if !comment.value.nil? %>
            <p> Value change: <%= comment.value %>% </p>
            <% end %>




          </div>

          <% if current_user != nil %>
            <% if current_user.admin? %>

              <div class="commentinfo">
              <p>Admin Buttons</p>
              <%= link_to "Edit Comment", edit_coin_comment_path(@coin, comment), class: 'button'  %>
              <%= link_to "Delete Comment", coin_comment_path(@coin, comment), class: 'button', method: :delete, data: {confirm: 'Are your sure?'} %>
              </div>
            <% end %>
          <% end %>
          </div>
        </div>
      <% end %>
    </ul>

app/views/comments/edit.html.erb
<div class="edit-user"><h2 id="edit">Comment for <%= @coin.name %></h2>
<%= form_for [@coin, @comment] do |f| %>

<div class="field">
  <%= f.label :title %>
  <%= f.text_area :title %>
</div>

<div class="field">
  <%= f.label :body, "Description" %>
  <%= f.text_area :body %>
</div>

<div class="field">
  <%= f.label :rating, "Rating" %>
  <%= f.text_area :rating %>
</div>

<div class="field">
  <%= f.label :date, "Please enter date of initial coin investment (dd/mm/yyyy)" %>
  <%= f.text_area :date %>
</div>

<div class="field">
  <%= f.label :initial_coin_deposit, "Please enter the amount of dollars invested in USD" %>
  <%= f.text_area :initial_coin_deposit %>
</div>




<div class="actions">
  <%= f.submit "Add Comment" %>
</div>

<% end %>
</div>

app/views/comments/new.html.erb
<div class="edit-user"><h2 id="edit">Comment for <%= @coin.name %></h2>
<%= form_for [@coin, @comment] do |f| %>

<div class="field">
  <%= f.label :title %>
  <%= f.text_area :title %>
</div>

<div class="field">
  <%= f.label :body, "Description" %>
  <%= f.text_area :body %>
</div>

<div class="field">
  <%= f.label :rating, "Stability Rating (Please select 1-5, from Worst to Best)" %>
  <%= f.text_area :rating %>
</div>

<div class="field">
  <%= f.label :date, "Please enter date of initial coin investment (yyyy-mm-dd)" %>
  <%= f.text_area :date %>
</div>

<div class="field">
  <%= f.label :initial_coin_deposit, "Please enter the amount of coins invested" %>
  <%= f.text_area :initial_coin_deposit %>
</div>


<div class="actions">
  <%= f.submit "Add Comment" %>
</div>

<% end %>
</div>

app/views/comments/show.html.erb
<p>comment show page</p>

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/css?family=Russo+One" rel="stylesheet">
  <title>Cryptovest</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
  <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= javascript_include_tag "vendor/modernizr" %>

  <%= csrf_meta_tags %>
</head>
<%= javascript_pack_tag 'application' %>
<body class="background">

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Cryptovest</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <li><%= link_to 'Your Profile', edit_user_registration_path %></li>
          <li><%= image_tag(current_user.avatar.thumb)  %> </li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/users/index.html.erb
<p>index of users</p>

<% @users.each do |user| %>
  <li>
    <%= link_to user.email, user %>
    <p>Email: <%= user.email %></p>
    <p>Type: <%= user.role %> </p>
  </li>
<% end %>

app/views/users/show.html.erb
<h1>Your Page</h1>

<p id="notice"><%= notice %></p>

  <%= form_for @user, html: { multipart: true } do |f| %>
  <p>
    <label>Your Profile Pic</label>
    <%if current_user.avatar.present? %>
    <%= image_tag(@user.avatar) %>
    <%end %>
    <%= f.file_field :avatar %>
  </p>

  <div class="actions">
    <% if current_user.avatar.present? %>
    <%= f.submit "Change Picture" %>
    <% else %>
    <%= f.submit "Add Picture" %>
    <%end%>
  </div>
<% end %>

<p>user show page</p>
<p>Email: <%= @user.email %></p>
<p>Type: <%= @user.role %>
<button> <%= link_to "Delete User", users_path, method: :delete, data: {confirm: 'Are your sure?'} %> </button>

app/views/users/update.html.erb
<h1>Updated</h1>

<p>
<%= image_tag(@user.avatar) %>
</p>